v1.0

diff --git a/redhat/ipchanger b/redhat/ipchanger
--- a/redhat/ipchanger
+++ b/redhat/ipchanger
@@ -3,6 +3,7 @@
 ########################################################################################################
 # Interface path "/etc/sysconfig/network-scripts" is default.
 INTPATH='/etc/sysconfig/network-scripts'
+GATEPATH='/etc/sysconfig/network' # Gateway path
 # Color code
 declare -r DEF='\e[0m'     # Default
 declare -r RED='\e[31m'    # Red
@@ -51,7 +52,9 @@ function DHCP() {
 	GetLineNumber
 	bootproto=`grep "BOOTPROTO=" "$INTPATH" | cut -d'=' -f2`
 	if [[ `sed -n "${lineIP}p" "$INTPATH"` =~ "IPADDR" ]]; then sed -i "${lineIP}d" "$INTPATH"; fi # Remove address line
-	if [[ `sed -n "${lineMask}p" "$INTPATH"` =~ "NETMASK" ]]; then sed -i "${lineMask}d" "$INTPATH"; fi
+	GetLineNumber
+	if [[ `sed -n "${lineMask}p" "$INTPATH"` =~ "NETMASK" ]]; then sed -i "${lineMask}d" "$INTPATH"; fi # Remove NETMASK
+	if [[ `sed -n "${lineGW}p" "$GATEPATH"` =~ "GATEWAY" ]]; then sed -i "${lineGW}d" "$GATEPATH"; fi # Remove GATEWAY
 	sed -i "${line}s/static/dhcp/" "$INTPATH" && echo "Static -> DHCP" || echo -e "${RED}Can't change to DHCP mode${DEF}" # Change static to dhcp
 	Refresh
 } # Set to dhcp
@@ -85,31 +88,24 @@ function GetLineNumber() {
 	line=`grep -n "BOOTPROTO=" "$INTPATH" | cut -d':' -f1`
 	lineMask=`grep -n "NETMASK=" "$INTPATH" | cut -d':' -f1`
 	lineIP=`grep -n "IPADDR=" "$INTPATH" | cut -d':' -f1`
+	lineGW=`grep -n "GATEWAY=" "$GATEPATH" | cut -d':' -f1`
 } # Get line number of address, netmask and boot protocol(static or dhcp).
 function WriteChange() {
-	if grep -Fq "$UINT" "$INTPATH"; then
 		GetLineNumber
-		if [[ `sed -n "${inarr[0]}p" "$INTPATH"` =~ "dhcp" ]]; then sed -i "${inarr[0]}s/dhcp/static/" "$INTPATH" && echo "DHCP -> static" || echo -e "${RED}Can't change to static mode${DEF}"; fi
-		if [[ $cip > `wc -l $INTPATH | cut -d' ' -f1` ]]; then
-			echo -e "\taddress $IP" >> "$INTPATH" && echo -e "IPv4 -> ${GREEN}OK${DEF}" || echo -e "IPv4 -> ${RED}FAILED${DEF}"
-            		echo -e "\tnetmask $netMask" >> "$INTPATH" && echo -e "Netmask -> ${GREEN}OK${DEF}" || echo -e "Netmask -> ${RED}FAILED${DEF}"
-			if ! [[ $3 == "" ]]; then echo -e "\tgateway $GW" >> "$INTPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"; fi
+		if [[ `sed -n "${line}p" "$INTPATH"` =~ "dhcp" ]]; then sed -i "${line}s/dhcp/static/" "$INTPATH" && echo "DHCP -> static" || echo -e "${RED}Can't change to static mode${DEF}"
+			echo -e "IPADDR=$IP" >> "$INTPATH" && echo -e "IPv4 -> ${GREEN}OK${DEF}" || echo -e "IPv4 -> ${RED}FAILED${DEF}"
+            		echo -e "NETMASK=$netMask" >> "$INTPATH" && echo -e "Netmask -> ${GREEN}OK${DEF}" || echo -e "Netmask -> ${RED}FAILED${DEF}"
+			if ! [[ $3 == "" ]]; then echo -e "GATEWAY=$GW" >> "$GATEPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"; fi
 			Refresh
-		fi # If is the last interface of file (need append instead of replace)
-		sed -i "${cip}s/.*/\taddress $IP/" "$INTPATH" && echo -e "IPv4 -> ${GREEN}OK${DEF}" || echo -e "IPv4 -> ${RED}FAILED${DEF}" # Replace a line by number
-		sed -i "${cnet}s/.*/\tnetmask $netMask/" "$INTPATH" && echo -e "Netmask -> ${GREEN}OK${DEF}" || echo -e "Netmask -> ${RED}FAILED${DEF}"
-		if ! [[ $3 == "" ]]; then
-			if [[ `sed -n "${cgw}p" "$INTPATH"` =~ "gateway" ]]; then sed -i "${cgw}s/.*/\tgateway $GW/" "$INTPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"
-		    	else sed -i -e "${cnet}s/$/\n\tgateway $GW/" "$INTPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"; fi # Insert line after
-		else if [[ `sed -n "${cgw}p" "$INTPATH"` =~ "gateway" ]]; then sed -i "${cgw}d" "$INTPATH" && echo -e "Gateway -> ${GREEN}REMOVED${DEF}" || echo -e "Gateway -> ${RED}CANNOT BE REMOVED${DEF}" ; fi # Remove if applicable, last gateway set #1.3
+		else # If is in dhcp. Need to add line IPADDR and NETMASK.
+			sed -i "${lineIP}s/.*/IPADDR=$IP/" "$INTPATH" && echo -e "IPv4 -> ${GREEN}OK${DEF}" || echo -e "IPv4 -> ${RED}FAILED${DEF}" # Replace a line by linenumber
+			sed -i "${lineMask}s/.*/NETMASK=$netMask/" "$INTPATH" && echo -e "Netmask -> ${GREEN}OK${DEF}" || echo -e "Netmask -> ${RED}FAILED${DEF}"
 		fi
-	else
-		echo "auto $UINT" >> "$INTPATH" && echo -e "${GREEN}$UINT added to $INTPATH file${DEF}" || echo -e "${RED}CANNOT ADD $UINT TO $INTPATH${DEF}"
-		echo "iface $UINT inet static" >> "$INTPATH"
-		echo -e "\taddress $IP" >> "$INTPATH" && echo -e "IPv4 -> ${GREEN}OK${DEF}" || echo -e "IPv4 -> ${RED}FAILED${DEF}"
-		echo -e "\tnetmask $netMask" >> "$INTPATH" && echo -e "Netmask -> ${GREEN}OK${DEF}" || echo -e "Netmask -> ${RED}FAILED${DEF}"
-		if ! [[ $3 == "" ]]; then echo -e "\tgateway $GW" >> "$INTPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"; fi
-	fi
+		if ! [[ $3 == "" ]]; then
+			if [[ `sed -n "${lineGW}p" "$GATEPATH"` =~ "GATEWAY=" ]]; then sed -i "${lineGW}s/.*/GATEWAY=$GW/" "$GATEPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"
+		    	else echo "GATEWAY=$GW" >> "$GATEPATH" && echo -e "Gateway -> ${GREEN}OK${DEF}" || echo -e "Gateway -> ${RED}FAILED${DEF}"; fi # Insert line after
+		elif [[ `sed -n "${lineGW}p" "$GATEPATH"` =~ "GATEWAY" ]]; then sed -i "${lineGW}d" "$GATEPATH" && echo -e "Gateway -> ${GREEN}REMOVED${DEF}" || echo -e "Gateway -> ${RED}CANNOT BE REMOVED${DEF}" # Remove if applicable, last gateway set #1.3
+		fi
 }
 if [[ $1 =~ '-h' ]]; then
     echo "Syntax when asking for IP: ip/prefix OR ip/prefix/gateway OR dhcp"
